# Generated by Django 3.1.2 on 2020-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('input_url', models.TextField(blank=True)),
                ('image_hash', models.CharField(default='DEFAULT VALUE', max_length=32, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
