# Generated by Django 3.1.2 on 2020-10-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_resizer', '0002_auto_20201011_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_hash',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
