# Generated by Django 3.1.2 on 2020-10-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_resizer', '0003_auto_20201011_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
